# /etc/nginx/sites-available/myapp.conf

upstream myapp {
  server unix:/var/www/myapp/shared/tmp/sockets/puma.sock;
}

server {

  server_name https://railway.app;
  root /var/www/myapp/current/public;
  access_log /var/log/nginx/https://railway.app_access.log;
  error_log /var/log/nginx/https://railway.app_error.log;

  location / {
    proxy_pass https://railway.app;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location ~* ^/assets/ {
    expires 1y;
    add_header Cache-Control public;
    add_header ETag "";
    break;
  }

  location ^~ /health {
    access_log off;
    return 200 'OK';
  }

  location ^~ /healthz {
    access_log off;
    return 200 'OK';
  }

  location ~* ^/[a-z0-9]{8}/ {
    expires 1d;
    add_header Cache-Control public;
    add_header ETag "";
    break;
  }

  location ~* ^/[a-z0-9]{32}/ {
    expires 1d;
    add_header Cache-Control public;
    add_header ETag "";
    break;
  }

  location ~* ^/[a-z0-9]{64}/ {
    expires 1d;
    add_header Cache-Control public;
    add_header ETag "";
    break;
  }

  location ~* ^/[a-z0-9]{40}/ {
    expires 1d;
    add_header Cache-Control public;
    add_header ETag "";
    break;
  }

  location ~* \.(jpg|jpeg|gif|png|css|js|ico|html)$ {
    expires 1d;
    add_header Cache-Control public;
    add_header ETag "";
  }

  location ~* \.(pdf|avi|mov|mp3|mp4|mpeg|flv|swf)$ {
    expires 1d;
    add_header Cache-Control public;
    add_header ETag "";
  }

  location ~* \.(eot|ttf|woff)$ {
    expires 1d;
    add_header Cache-Control public;
    add_header ETag "";
  }

  location ~* \.(svg)$ {
    expires 1d;
    add_header Cache-Control public;
    add_header ETag "";
  }

  location ~* \.(zip|gz|gzip|bz2|csv|xls|doc|docx|ppt|pptx|tar|xml
}
